/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n9.0.1-11-ge47273f4d9-20260901"
#endif /* AVUTIL_FFVERSION_H */
